/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness */
        get: operations["healthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/node/v1/connect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Alias of /v1/node */
        get: operations["nodeConnectAlias"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/push/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["pushConfig"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/push/subscriptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["pushSubscribe"];
        delete: operations["pushUnsubscribe"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["deviceList"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/devices/pair": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["devicePairRedeem"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/devices/pair-code": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["devicePairCode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/devices/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deviceRevoke"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/fleet/broadcast": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["fleetBroadcast"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/fleet/instances": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["fleetCreate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/fleet/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["fleetGet"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/fleet/{id}/commands": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["fleetCommands"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/follow": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** WebSocket snapshot + live journal */
        get: operations["follow"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/hosts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List enrolled hosts */
        get: operations["hostList"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/hosts/ssh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Persist a Hub-supervised SSH host and start preflight/reconnect */
        post: operations["hostSshAdd"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/hosts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Host inventory */
        get: operations["hostGet"];
        put?: never;
        post?: never;
        /** Remove a supervised SSH host after stopping its instances; keep journal history */
        delete: operations["hostRemove"];
        options?: never;
        head?: never;
        patch: operations["hostPatch"];
        trace?: never;
    };
    "/v1/instances": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["instanceList"];
        put?: never;
        post: operations["instanceCreate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/instances/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["instanceGet"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/instances/{id}/commands": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["instanceCommand"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/instances/{id}/journal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["instanceJournal"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/interactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Pending interactions across connected hosts */
        get: operations["interactionList"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/interactions/{id}/answer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["interactionAnswer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Bootstrap token → device cookie */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/node": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Node JSON-RPC WebSocket */
        get: operations["nodeSocket"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/placement/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["placementResolve"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List provider profiles (secret never returned) */
        get: operations["providerList"];
        put?: never;
        /** Create a gateway or direct profile; authToken stored encrypted */
        post: operations["providerCreate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/providers/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["providerGet"];
        put?: never;
        post?: never;
        delete: operations["providerDelete"];
        options?: never;
        head?: never;
        /** Update metadata and/or rotate authToken */
        patch: operations["providerPatch"];
        trace?: never;
    };
    "/v1/providers/{id}/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Probe models list / reachability against the gateway */
        post: operations["providerTest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/worktrees": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List git worktrees on a host (Node remuda worktree catalog) */
        get: operations["worktreeList"];
        put?: never;
        /** Create a git worktree on a host (`git worktree add -b wt/<name>/…` from main) */
        post: operations["worktreeCreate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CommandRecord: {
            commandId: string;
            createdAt?: string;
            forwarded?: boolean;
            hostId: string;
            instanceId?: string | null;
            operation: string;
            resolution?: string;
            state: string;
            updatedAt?: string;
        } & {
            [key: string]: unknown;
        };
        CommandRequest: {
            commandId?: string;
            idempotencyKey?: string;
            operation?: string;
            payload?: {
                [key: string]: unknown;
            };
            prompt?: string;
        };
        CommandResult: {
            command: components["schemas"]["CommandRecord"];
            replayed?: boolean;
        };
        Device: {
            id: string;
            name: string;
        };
        DevicePage: {
            items: components["schemas"]["Device"][];
        };
        DeviceSession: {
            deviceId: string;
            name: string;
            token: string;
        };
        ErrorBody: {
            code: string;
            error: string;
            reasons?: string[];
        };
        /** @description Select running instances and fan one command out. Requires `all` or at least one of `hosts` / `labels` / `kinds`; filters intersect. */
        FleetBroadcast: {
            all?: boolean;
            hosts?: string[];
            /** @description Base key; each instance is queued under `<key>:<instanceId>` so a retry replays instead of double-sending. */
            idempotencyKey?: string;
            kinds?: string[];
            labels?: string[];
            /** @enum {string} */
            operation?: "instance.send" | "tty.write";
            payload?: {
                [key: string]: unknown;
            };
        };
        FleetBroadcastResult: {
            accepted?: number;
            failed?: number;
            operation?: string;
            results?: {
                commandId?: string;
                error?: string;
                forwarded?: boolean;
                hostId?: string;
                instanceId?: string;
                kind?: string;
                ok?: boolean;
                replayed?: boolean;
                resolution?: string | null;
                state?: string;
            }[];
            selected?: number;
            skipped?: number;
        };
        FleetCreate: {
            driver?: string;
            hosts?: string[];
            kind?: string;
            labels?: string[];
            max?: number;
            prompt?: string;
            spec?: {
                [key: string]: unknown;
            };
        };
        FleetCreateResult: {
            fleetId?: string;
            instanceIds?: string[];
        };
        HostCli: {
            /** @enum {string} */
            auth?: "logged_in" | "logged_out" | "unknown";
            kind: string;
            path?: string | null;
            version?: string | null;
        } & {
            [key: string]: unknown;
        };
        HostPage: {
            items: components["schemas"]["HostView"][];
            nextCursor?: string | null;
        };
        HostPatch: {
            labels?: string[];
            maxInstances?: number;
            name?: string;
        };
        HostView: {
            capabilities?: {
                [key: string]: unknown;
            };
            cli?: components["schemas"]["HostCli"][];
            herdr?: {
                [key: string]: unknown;
            } | null;
            /** @description Stable Node identity (`hst_…`). */
            hostId: string;
            hostname?: string | null;
            id?: string;
            instanceCount?: number;
            label: string;
            labels?: string[];
            lastError?: string | null;
            lastSeenAt?: string | null;
            maxInstances?: number;
            name?: string;
            nodeVersion?: string | null;
            online: boolean;
            resources?: {
                [key: string]: unknown;
            } | null;
            ssh?: {
                /**
                 * @default require_installed
                 * @enum {string}
                 */
                remudaBinaryPolicy: "require_installed" | "upload_if_missing";
                target: string;
                workspaceRoot?: string;
            } | null;
            state: string;
            transport?: string;
        } & {
            [key: string]: unknown;
        };
        InstanceCreate: {
            claudeConfigDir?: string;
            /** @description Working directory on the host. */
            cwd?: string;
            delegation?: string;
            driver?: string;
            hostId?: string;
            kind?: string;
            maxBudgetUsd?: string | number;
            model?: string;
            name?: string;
            permissionMode?: string;
            placement?: {
                [key: string]: unknown;
            };
            prompt?: string;
            providerProfileId?: string;
            settingsOverlayPath?: string;
            title?: string;
            workspaceId?: string;
            /** @description Worktree name created by remuda worktree create. */
            worktree?: string;
        };
        InstanceCreateResult: {
            command: components["schemas"]["CommandRecord"];
            hostId?: string;
            instance: components["schemas"]["InstanceRecord"];
        };
        InstancePage: {
            items: components["schemas"]["InstanceRecord"][];
            nextCursor?: string | null;
        };
        InstanceRecord: {
            /**
             * @description idle only after a Node/herdr agent_status or session idle observation. Create default is unknown.
             * @enum {string}
             */
            activity: "unknown" | "idle" | "working" | "blocked" | "draining";
            connectivity: string;
            createdAt?: string;
            cwd?: string | null;
            delegation?: string | null;
            driver: string;
            durableSeq: string;
            hostId: string;
            instanceId: string;
            journalId: string;
            kind: string;
            /**
             * @description Derived from Node lifecycle observations in journal.append. Create default is requested, not running.
             * @enum {string}
             */
            lifecycle: "requested" | "starting" | "running" | "closing" | "exited" | "failed";
            name?: string | null;
            providerProfileId?: string | null;
            title?: string | null;
            updatedAt?: string;
            workspaceId?: string | null;
        } & {
            [key: string]: unknown;
        };
        InteractionAnswerRequest: {
            answer: {
                [key: string]: unknown;
            };
            commandId?: string;
        };
        InteractionPage: {
            items: {
                [key: string]: unknown;
            }[];
            nextCursor?: string | null;
        };
        JournalPage: {
            durableSeq: string;
            events: {
                [key: string]: unknown;
            }[];
            instanceId: string;
        };
        LoginRequest: {
            bootstrapToken: string;
            deviceName?: string;
        };
        PairCode: {
            code: string;
            expiresAt: string;
        };
        PairRedeem: {
            code: string;
            deviceName?: string;
        };
        PlacementResolve: {
            delegation?: string;
            driver?: string;
            hostId?: string;
            placement?: {
                [key: string]: unknown;
            };
        } & {
            [key: string]: unknown;
        };
        ProviderCreate: {
            authToken: string;
            baseUrl?: string;
            defaultGateway?: boolean;
            defaultModel?: string;
            headers?: {
                [key: string]: string;
            };
            /** @enum {string} */
            kind?: "gateway" | "direct";
            models?: string[];
            name: string;
        };
        ProviderHealth: {
            checkedAt?: string | null;
            latencyMs?: number | null;
            message?: string | null;
            ok: boolean;
            status?: number | null;
        };
        ProviderPage: {
            items: components["schemas"]["ProviderProfile"][];
            nextCursor?: string | null;
        };
        ProviderPatch: {
            /** @description Rotate the stored token. */
            authToken?: string;
            baseUrl?: string;
            defaultGateway?: boolean;
            defaultModel?: string | null;
            headers?: {
                [key: string]: string;
            };
            /** @enum {string} */
            kind?: "gateway" | "direct";
            models?: string[];
            name?: string;
        };
        ProviderProfile: {
            baseUrl: string;
            createdAt?: string;
            defaultGateway: boolean;
            defaultModel?: string | null;
            headers?: {
                [key: string]: string;
            };
            health?: components["schemas"]["ProviderHealth"] | null;
            id: string;
            /** @enum {string} */
            kind: "gateway" | "direct";
            models: string[];
            name: string;
            revision: string;
            secret: components["schemas"]["ProviderSecretView"];
            updatedAt?: string;
        };
        ProviderSecretView: {
            fingerprint?: string | null;
            last4?: string | null;
            present: boolean;
        };
        ProviderTestResult: {
            latencyMs?: number;
            message: string;
            models?: string[];
            ok: boolean;
            reachable: boolean;
            status?: number | null;
        };
        PushSubscribe: {
            deviceId?: string;
            endpoint: string;
            keys: {
                auth: string;
                p256dh: string;
            };
        };
        SshHostCreate: {
            label: string;
            /** @description Placement labels such as egress:gateway or region=sg. */
            labels?: string[];
            /**
             * @default require_installed
             * @enum {string}
             */
            remuda_binary_policy: "require_installed" | "upload_if_missing";
            /** @description SSH config alias or user@host, resolved by the Hub system SSH client. */
            target: string;
        };
        WorktreeCreate: {
            /** @description Start-point (default main). */
            base?: string;
            hostId?: string;
            name: string;
            path?: string;
            repo?: string;
        };
        WorktreePage: {
            hostId?: string;
            items: components["schemas"]["WorktreeRecord"][];
            nextCursor?: string | null;
            workspaceRoot?: string | null;
        };
        WorktreeRecord: {
            base?: string;
            branch?: string;
            hostId?: string;
            name: string;
            path: string;
            workspaceRoot?: string;
        };
    };
    responses: {
        /** @description Hub error */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorBody"];
            };
        };
    };
    parameters: {
        IdPath: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ok: boolean;
                    };
                };
            };
        };
    };
    nodeConnectAlias: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Switching Protocols */
            101: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    pushConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description VAPID public key */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        public_key: string;
                    };
                };
            };
            401: components["responses"]["Error"];
        };
    };
    pushSubscribe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PushSubscribe"];
            };
        };
        responses: {
            /** @description Stored */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ok?: boolean;
                    };
                };
            };
        };
    };
    pushUnsubscribe: {
        parameters: {
            query: {
                endpoint: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Removed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ok?: boolean;
                    };
                };
            };
        };
    };
    deviceList: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Devices */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DevicePage"];
                };
            };
        };
    };
    devicePairRedeem: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PairRedeem"];
            };
        };
        responses: {
            /** @description New device session */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceSession"];
                };
            };
            401: components["responses"]["Error"];
        };
    };
    devicePairCode: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One-time code */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PairCode"];
                };
            };
        };
    };
    deviceRevoke: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Revoked */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ok: boolean;
                    };
                };
            };
            404: components["responses"]["Error"];
        };
    };
    fleetBroadcast: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["FleetBroadcast"];
            };
        };
        responses: {
            /** @description Per-instance fan-out results with an accepted/failed summary */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FleetBroadcastResult"];
                };
            };
            400: components["responses"]["Error"];
        };
    };
    fleetCreate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["FleetCreate"];
            };
        };
        responses: {
            /** @description Fleet */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FleetCreateResult"];
                };
            };
            422: components["responses"]["Error"];
        };
    };
    fleetGet: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Fleet aggregate */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            404: components["responses"]["Error"];
        };
    };
    fleetCommands: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["CommandRequest"];
            };
        };
        responses: {
            /** @description Per-instance commands */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    follow: {
        parameters: {
            query?: {
                instanceId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Switching Protocols */
            101: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    hostList: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Host page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HostPage"];
                };
            };
            401: components["responses"]["Error"];
        };
    };
    hostSshAdd: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SshHostCreate"];
            };
        };
        responses: {
            /** @description Host registered; inspect state and lastError while connecting */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HostView"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    hostGet: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Host */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HostView"];
                };
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    hostRemove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Supervisor cancelled, connection closed, registration removed; remote files retained */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    hostPatch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["HostPatch"];
            };
        };
        responses: {
            /** @description Updated host */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HostView"];
                };
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    instanceList: {
        parameters: {
            query?: {
                hostId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Instance page. lifecycle is derived from Node journal observations (requested→starting→running→exited/failed). activity=idle only after a herdr/Node idle observation, never the create default. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstancePage"];
                };
            };
            401: components["responses"]["Error"];
        };
    };
    instanceCreate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InstanceCreate"];
            };
        };
        responses: {
            /** @description Created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstanceCreateResult"];
                };
            };
            401: components["responses"]["Error"];
            422: components["responses"]["Error"];
        };
    };
    instanceGet: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Instance */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstanceRecord"];
                };
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    instanceCommand: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CommandRequest"];
            };
        };
        responses: {
            /** @description Command ledger row */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommandResult"];
                };
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    instanceJournal: {
        parameters: {
            query?: {
                afterSeq?: string;
            };
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Mirrored journal */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JournalPage"];
                };
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    interactionList: {
        parameters: {
            query?: {
                hostId?: string;
                instanceId?: string;
                kind?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Interaction page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InteractionPage"];
                };
            };
            401: components["responses"]["Error"];
        };
    };
    interactionAnswer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InteractionAnswerRequest"];
            };
        };
        responses: {
            /** @description First-answer-wins result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Device session */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceSession"];
                };
            };
            401: components["responses"]["Error"];
        };
    };
    nodeSocket: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Switching Protocols */
            101: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    placementResolve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PlacementResolve"];
            };
        };
        responses: {
            /** @description Ranked hosts */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            422: components["responses"]["Error"];
        };
    };
    providerList: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Provider page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderPage"];
                };
            };
            401: components["responses"]["Error"];
        };
    };
    providerCreate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProviderCreate"];
            };
        };
        responses: {
            /** @description Created profile (fingerprint/last4 only) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderProfile"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
        };
    };
    providerGet: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Profile */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderProfile"];
                };
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    providerDelete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ok: boolean;
                    };
                };
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    providerPatch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProviderPatch"];
            };
        };
        responses: {
            /** @description Updated profile */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderProfile"];
                };
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    providerTest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Probe result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderTestResult"];
                };
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    worktreeList: {
        parameters: {
            query?: {
                hostId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Worktree page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorktreePage"];
                };
            };
            401: components["responses"]["Error"];
        };
    };
    worktreeCreate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorktreeCreate"];
            };
        };
        responses: {
            /** @description Created or reused worktree */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorktreeRecord"];
                };
            };
            401: components["responses"]["Error"];
            422: components["responses"]["Error"];
        };
    };
}
