//! Disposable native Node for the promoted-hook Hub e2e fixture.
//!
//! Required fixture-only inputs: `HUB_E2E_NODE_HUB_URL`,
//! `HUB_E2E_NODE_TOKEN_FILE`, `HUB_E2E_NODE_WORKSPACE`,
//! `HUB_E2E_NODE_DATA_DIR`, and `HUB_E2E_REMUDA_BIN`. The existing
//! `REMUDA_CLAUDE_BIN` and `REMUDA_CLAUDE_CONFIG_DIR` must point to the
//! fake-harness executable and isolated Claude home created by the spec.
//! Only scheduling resources and the host label are synthetic: the runtime,
//! native PTY, launch shim, hook relay, and Hub dispatch are production code.

use anyhow::{Context, Result, ensure};
use remuda_node::{
    Backoff, CollectRequest, Collector, DevServerConfig, LocalDrivers, NativeDriverConfig,
    ProbeEnv, ResourceReport, ServeConfig, WssConfig, WssLink, compose,
};
use serde_json::json;
use std::{collections::BTreeMap, path::PathBuf, time::Duration};

const LABEL: &str = "e2e-native-hooks";
const SHUTDOWN_TIMEOUT: Duration = Duration::from_secs(8);

fn required_path(key: &str) -> Result<PathBuf> {
    let path = PathBuf::from(std::env::var_os(key).with_context(|| format!("missing {key}"))?);
    ensure!(path.is_absolute(), "{key} must be absolute");
    ensure!(path.exists(), "{key} must already exist");
    Ok(path)
}

#[cfg(not(unix))]
fn main() -> Result<()> {
    anyhow::bail!("native_hub_e2e requires a Unix PTY host")
}

#[cfg(unix)]
#[tokio::main]
async fn main() -> Result<()> {
    use tokio::signal::unix::{SignalKind, signal};

    // Register before enrollment so the Playwright cleanup can also stop a
    // fixture whose initial Hub connection has not completed.
    let mut terminate = signal(SignalKind::terminate())?;
    let mut interrupt = signal(SignalKind::interrupt())?;
    let url = reqwest::Url::parse(
        &std::env::var("HUB_E2E_NODE_HUB_URL").context("missing HUB_E2E_NODE_HUB_URL")?,
    )
    .context("invalid fixture Hub URL")?;
    ensure!(
        url.scheme() == "ws"
            && matches!(url.host_str(), Some("127.0.0.1" | "[::1]" | "::1"))
            && url.port().is_some()
            && url.path() == "/v1/node"
            && url.username().is_empty()
            && url.password().is_none()
            && url.query().is_none()
            && url.fragment().is_none(),
        "fixture Hub URL must be ws://<loopback>:<port>/v1/node"
    );
    let token_file = required_path("HUB_E2E_NODE_TOKEN_FILE")?;
    let workspace = required_path("HUB_E2E_NODE_WORKSPACE")?;
    // Preserve the caller's short volfs/procfs alias: canonicalizing it can
    // fail on macOS or exceed the Unix hook socket pathname limit.
    let data_dir = required_path("HUB_E2E_NODE_DATA_DIR")?;
    let relay = required_path("HUB_E2E_REMUDA_BIN")?;
    let claude = required_path("REMUDA_CLAUDE_BIN")?;
    let claude_home = required_path("REMUDA_CLAUDE_CONFIG_DIR")?;
    ensure!(
        workspace.is_dir() && data_dir.is_dir() && claude_home.is_dir(),
        "fixture workspace, data directory, and Claude home must be directories"
    );
    ensure!(
        relay.is_file() && claude.is_file(),
        "fixture relay and fake Claude must be files"
    );
    let token = std::fs::read_to_string(token_file).context("read fixture enrollment token")?;
    ensure!(
        !token.trim().is_empty(),
        "fixture enrollment token is empty"
    );

    // The collector's injectable view avoids probing the user's real CLIs or
    // auth markers. The fake binary still supplies its normal CLI inventory.
    let probe = ProbeEnv {
        path: claude
            .parent()
            .context("fake Claude executable has no parent")?
            .as_os_str()
            .to_owned(),
        home: claude_home.clone(),
        hostname: Some(LABEL.into()),
        herdr_socket_env: None,
        xdg_config_home: Some(data_dir.join("fixture-config")),
    };
    let mut inventory = Collector::new(probe, Duration::ZERO).snapshot(&CollectRequest {
        labels: BTreeMap::from([("test".into(), "promoted-hooks".into())]),
        max_instances: 8,
        herdr_socket: None,
    });
    inventory.cli.retain(|entry| entry.path.is_some());
    // Keep the production placement policy intact while making this single
    // synthetic host independent of load generated by parallel CI builds.
    inventory.resources = ResourceReport {
        cpu_count: 1,
        mem_bytes: None,
        cpu_pct: Some(0),
        load_avg1: Some(0.0),
        mem_pct: Some(0),
        disk_free_gb: None,
    };

    let mut native = NativeDriverConfig::new(data_dir.clone())
        .with_claude_binary(claude)
        .with_claude_native_home(claude_home);
    native.claude_print_inherit_default_config = false;
    native.pty_hooks = true;
    native.promote_terminal_agents = true;
    native.herdr_orphan_sweep = false;
    // An example's current_exe cannot implement `remuda hook launch/emit`.
    // Use the public split-packaging option to re-enter the actual CLI.
    native.relay_binary = Some(Box::new(relay));
    let runtime = compose(&ServeConfig {
        http: DevServerConfig::loopback(0)
            .with_workspace_root(workspace.clone())
            .with_workspace_roots(vec![workspace]),
        data_dir,
        drivers: LocalDrivers::Native(native),
    })?;
    let host_id = runtime.host().meta.id.as_id().as_str().to_owned();
    let mut host = inventory.to_hub_host();
    host["hostId"] = json!(host_id);
    let config = WssConfig {
        url: url.into(),
        token: token.trim().to_owned(),
        host_id,
        label: LABEL.into(),
        node_version: env!("CARGO_PKG_VERSION").into(),
        cli: inventory.cli_hub_json(),
        host: Some(host),
        heartbeat_interval: Duration::from_secs(15),
        backoff: Backoff::default(),
        journal_queue: 32,
    };
    let session: Result<Option<WssLink>> = async {
        runtime.reconcile_herdr().await?;
        let link = tokio::select! {
            result = WssLink::connect_runtime(config, runtime.clone()) => result?,
            _ = terminate.recv() => return Ok(None),
            _ = interrupt.recv() => return Ok(None),
        };
        eprintln!("NATIVE_HUB_E2E_READY hostId={}", link.host_id);
        tokio::select! {
            _ = terminate.recv() => {},
            _ = interrupt.recv() => {},
        }
        Ok(Some(link))
    }
    .await;
    // Reclaim native drivers before disconnecting, including a partial launch
    // or enrollment error. The spec removes its files after this process exits.
    let stopped = tokio::time::timeout(SHUTDOWN_TIMEOUT, runtime.shutdown())
        .await
        .context("fixture native driver shutdown timed out")
        .and_then(|result| result.map_err(Into::into));
    if let Ok(Some(link)) = session.as_ref() {
        eprintln!("NATIVE_HUB_E2E_STOPPING hostId={}", link.host_id);
    }
    match session {
        Ok(Some(link)) => link.shutdown().await,
        Ok(None) => {}
        Err(error) => {
            stopped?;
            return Err(error);
        }
    }
    stopped?;
    eprintln!("NATIVE_HUB_E2E_STOPPED");
    Ok(())
}
